export const MOCK_MAKERS = [
    {
        id: 1,
        name: 'Rajesh Kumar Vishwakarma',
        city: 'Kanpur',
        rating: 4.9,
        reviews: 127,
        years: 18,
        specialties: ['Beds', 'Wardrobes', 'Dining Tables'],
        verified: { siteVisit: true, gst: true, id: true },
        avatar: null,
        completionRate: 98,
        monthEarnings: 284500,
        totalOrders: 342,
    },
    {
        id: 2,
        name: 'Mohammad Salim',
        city: 'Saharanpur',
        rating: 4.8,
        reviews: 89,
        years: 22,
        specialties: ['Carved Doors', 'Display Units', 'Temple Mandirs'],
        verified: { siteVisit: true, gst: true, id: true },
        avatar: null,
        completionRate: 96,
        monthEarnings: 198000,
        totalOrders: 256,
    },
    {
        id: 3,
        name: 'Suresh Patel',
        city: 'Jodhpur',
        rating: 4.7,
        reviews: 64,
        years: 15,
        specialties: ['Sheesham Beds', 'Bookshelves', 'TV Units'],
        verified: { siteVisit: true, gst: true, id: true },
        avatar: null,
        completionRate: 94,
        monthEarnings: 156000,
        totalOrders: 178,
    },
    {
        id: 4,
        name: 'Arjun Lohar',
        city: 'Jaipur',
        rating: 4.9,
        reviews: 112,
        years: 20,
        specialties: ['Sofa Sets', 'Office Desks', 'Dining Sets'],
        verified: { siteVisit: true, gst: false, id: true },
        avatar: null,
        completionRate: 97,
        monthEarnings: 312000,
        totalOrders: 401,
    },
    {
        id: 5,
        name: 'Vikram Singh',
        city: 'Delhi',
        rating: 4.6,
        reviews: 53,
        years: 12,
        specialties: ['Modular Kitchens', 'Wardrobes', 'Shoe Racks'],
        verified: { siteVisit: true, gst: true, id: true },
        avatar: null,
        completionRate: 92,
        monthEarnings: 225000,
        totalOrders: 198,
    },
];

export const MOCK_QUOTES = [
    {
        id: 1,
        makerId: 1,
        material: { name: 'Sheesham Grade-A', cost: 12000 },
        labor: { days: 5, cost: 4500 },
        delivery: 2000,
        commissionRate: 0.08,
        gstRate: 0.18,
        estimatedDays: 12,
    },
    {
        id: 2,
        makerId: 2,
        material: { name: 'Teak Premium', cost: 18500 },
        labor: { days: 7, cost: 6300 },
        delivery: 2500,
        commissionRate: 0.08,
        gstRate: 0.18,
        estimatedDays: 15,
    },
    {
        id: 3,
        makerId: 3,
        material: { name: 'Mango Wood Select', cost: 8500 },
        labor: { days: 4, cost: 3600 },
        delivery: 1800,
        commissionRate: 0.08,
        gstRate: 0.18,
        estimatedDays: 10,
    },
];

export const MOCK_MESSAGES = [
    { id: 1, from: 'maker', text: 'Namaste! I received your bed specification. The Sheesham wood you want is available in Grade-A quality.', textHi: 'नमस्ते! मुझे आपका बेड स्पेसिफिकेशन मिला। आप जो शीशम की लकड़ी चाहते हैं वह ग्रेड-A गुणवत्ता में उपलब्ध है।', time: '10:32 AM', type: 'text' },
    { id: 2, from: 'user', text: 'Great! Can you share a photo of the wood sample?', textHi: 'बढ़िया! क्या आप लकड़ी के नमूने की फोटो शेयर कर सकते हैं?', time: '10:35 AM', type: 'text' },
    { id: 3, from: 'maker', text: '', time: '10:40 AM', type: 'photo', photoUrl: 'wood_sample' },
    { id: 4, from: 'maker', text: 'Here is the Sheesham plank I will use. Notice the grain quality.', textHi: 'यह शीशम का तख्ता है जो मैं उपयोग करूंगा। ग्रेन गुणवत्ता देखें।', time: '10:41 AM', type: 'text' },
    { id: 5, from: 'user', text: 'Looks beautiful! What about the headboard design?', textHi: 'बहुत सुंदर! हेडबोर्ड डिज़ाइन के बारे में क्या?', time: '10:45 AM', type: 'text' },
    { id: 6, from: 'maker', text: '', time: '10:48 AM', type: 'voice', duration: '0:34' },
    { id: 7, from: 'maker', text: 'I can do a classic panel design or a modern slatted style. The panel design will add ₹1,500 extra for carving.', textHi: 'मैं क्लासिक पैनल डिज़ाइन या मॉडर्न स्लैटेड स्टाइल बना सकता हूं। पैनल डिज़ाइन में नक्काशी के लिए ₹1,500 अतिरिक्त लगेगा।', time: '10:50 AM', type: 'text' },
];

export const MOCK_ORDERS = [
    {
        id: 'KG-2026-001',
        item: 'King Size Bed with Storage',
        maker: MOCK_MAKERS[0],
        status: 'in_progress',
        milestones: [
            { phase: 1, label: 'Raw Material', status: 'paid', amount: 7400, photoVerified: true },
            { phase: 2, label: 'Frame Complete', status: 'verified', amount: 8200, photoVerified: true },
            { phase: 3, label: 'Finishing & Delivery', status: 'pending', amount: 7976, photoVerified: false },
        ],
        totalAmount: 23576,
        startDate: '2026-03-15',
        expectedDate: '2026-04-10',
    },
    {
        id: 'KG-2026-002',
        item: '6-Seater Dining Table',
        maker: MOCK_MAKERS[1],
        status: 'in_progress',
        milestones: [
            { phase: 1, label: 'Raw Material', status: 'paid', amount: 11200, photoVerified: true },
            { phase: 2, label: 'Frame Complete', status: 'pending', amount: 10800, photoVerified: false },
            { phase: 3, label: 'Finishing & Delivery', status: 'pending', amount: 10300, photoVerified: false },
        ],
        totalAmount: 32300,
        startDate: '2026-03-20',
        expectedDate: '2026-04-18',
    },
];

export const MOCK_INCOMING_REQUESTS = [
    {
        id: 'REQ-101',
        customer: 'Ananya Sharma',
        item: 'Queen Bed with Hydraulic Storage',
        category: 'Bed',
        wood: 'Sheesham Grade-A',
        finish: 'Matte PU',
        dims: '78" × 60" × 36"',
        budget: '₹20,000 – ₹30,000',
        city: 'Delhi',
        date: '2026-04-02',
    },
    {
        id: 'REQ-102',
        customer: 'Rahul Verma',
        item: 'L-Shaped Office Desk',
        category: 'Desk',
        wood: 'Mango Wood',
        finish: 'Natural Oil',
        dims: '60" × 48" × 30"',
        budget: '₹12,000 – ₹18,000',
        city: 'Noida',
        date: '2026-04-01',
    },
];
